feat(counter): Add usage function, help option, and no-notification option to counter script
This commit adds a `usage` function, a `--help` option, and a `--no-notification` option to the `counter` script.
The `usage` function prints out a summary of how to use the script, including information about its options and positional arguments.
The `--help` option displays this usage summary when passed to the script.

The `--no-notification` option allows users to disable the desktop notification that is displayed when the countdown timer reaches zero. By default, the notification is enabled.

Additionally, this commit fixes a minor style issue by changing the shebang line from `#!/usr/bin/env sh` to `#!/bin/sh`.

diff --git a/counter b/counter
--- a/counter
+++ b/counter
@@ -1,13 +1,67 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
 # Dependencies
 # figlet
 # lolcat
 # libnotify
 
+usage() {
+	echo "Usage: $(basename "$0") [-n|--no-notification] [-t|--time seconds] [count]"
+	echo
+	echo "Options:"
+	echo "  -n, --no-notification    Disable desktop notification"
+	echo "  -t, --time seconds       Set the countdown time in seconds (default: 20)"
+	echo "  -h, --help               Show usage page"
+	echo
+	echo "Positional arguments:"
+	echo "  count                     Set the countdown time in seconds"
+	exit 2
+}
+
+# Defaults
+notification=true
 counter=20
 
-[ ! "$1" = "" ] && counter=$1
+TEMP=$(getopt \
+	--options 'nt:h' \
+	--long 'no-notification,time:,help' \
+	--name "$(basename "$0")" -- "$@")
+
+if [ $? -ne 0 ]; then
+	echo 'Terminating...' >&2
+	exit 1
+fi
+
+# Note the quotes around "$TEMP": they are essential!
+eval set -- "$TEMP"
+unset TEMP
+
+while true
+do
+	case "$1" in
+		'-n'|'--no-notification')
+			notification=false
+			shift
+			continue
+			;;
+		'-t'|'--time')
+			counter="$2"
+			shift 2
+			continue
+			;;
+		'-h'|'--help') usage ;;
+		'--')
+			shift
+			break
+			;;
+		*) # Option not dealt with
+			echo 'Internal error!' >&2
+			exit 1
+			;;
+	esac
+done
+
+[ -n "$1" ] && counter="$1"
 
 while [ "$counter" -gt 0 ]
 do
@@ -16,4 +70,4 @@ do
 	sleep 1
 done
 
-notify-send --urgency=critical "Time is up"
+$notification && notify-send --urgency=critical "Time is up"
