feat: Add file_type function and video thumbnail support in wallpaperLoop
This commit enhances the `wallpaperLoop` script with the following changes:

1. Added a new function `file_type` to determine the type of a given file based on its extension. This function helps identify whether a file is an image or a video.

2. Updated the `notify_wallpaper` function to handle video wallpapers. If the wallpaper is a video, the function generates a thumbnail image using `ffmpegthumbnailer` and sets it as the desktop notification icon.

3. Modified the `update_wallpaper` function to utilize the `file_type` function for identifying the wallpaper type.

These changes improve the functionality of `wallpaperLoop` by providing better handling of video wallpapers and enhancing the visual representation of notifications when a video wallpaper is selected.

diff --git a/wallpaperLoop b/wallpaperLoop
--- a/wallpaperLoop
+++ b/wallpaperLoop
@@ -43,12 +43,34 @@ debug_message() {
 	printf '\033['"$color"'m[%s]:\033[0m %s\n' "$1" "$2"
 }
 
+file_type() {
+	local type="$(echo "$1" | grep --max-count=1 --only-matching '\.[a-zA-Z]\{3,4\}$')"
+
+	case $type in
+		\.mkv | \.avi | \.m4v | \.mp4 | \.webm) type=video ;;
+		\.jpg | \.png | \.gif) type=image ;;
+		*)
+			debug_message 'ERROR' "Invalid filetype $type" >&2
+			return
+			;;
+	esac
+
+	echo "$type"
+}
+
 notify_wallpaper() {
 	local wallpaper_file="$(head -1 "$WALLPAPER")"
+	local type="$(file_type "$wallpaper_file")"
+	local icon_file="$wallpaper_file"
 
 	# TODO: video thumbnail for desktop notification icon
+	if [ "$type" = video ]
+	then
+		icon_file=/tmp/wallpaper-thumbnail.png
+		ffmpegthumbnailer -i "$wallpaper_file" -o "$icon_file" -s 0 -t "$(shuf --input-range=10-90 --head-count=1)%"
+	fi
 	notify-send \
-		--icon="$wallpaper_file" \
+		--icon="$icon_file" \
 		--urgency=low \
 		'Wallpaper Update' "$(basename "$wallpaper_file")"
 }
@@ -90,16 +112,7 @@ clear_screen() {
 
 update_wallpaper() {
 	local wallpaper_file="$(head -1 "$WALLPAPER")"
-	local type="$(grep --max-count=1 --only-matching '\.[a-zA-Z]\{3,4\}$' "$WALLPAPER")"
-
-	case $type in
-		\.mkv | \.avi | \.m4v | \.mp4 | \.webm) type=video ;;
-		\.jpg | \.png | \.gif) type=image ;;
-		*)
-			debug_message 'ERROR' "Invalid filetype $type"
-			return
-			;;
-	esac
+	local type="$(file_type "$wallpaper_file")"
 
 	if [ "$type" = video ] && ! $ENABLE_VIDEOS
 	then
